# @hdygURL = http://www.hzau.edu.cn/hdyg.htm

@hdygImageURL = http://www.hzau.edu.cn/info/1062/10753.htm
@hdygImageBadURL = http://www.hzau.edu.cn//info/1062/10781.htm

GET {{hdygImageBadURL}} HTTP/1.1